
project 'KMCAgoraARTCDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'KMCAgoraARTCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AgoraVRTCDemo
  pod 'libksygpulive/KSYGPUResource'
  pod 'libksygpulive/libksygpulive'
  pod 'Masonry'
  pod 'UICKeyChainStore', '~> 2.1.1'
  pod 'AgoraAudio_iOS', '~> 1.10.0'
end

